name: Nightly Tests

on:
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch:

env:
  GOPROXY: https://proxy.golang.org/

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      -
        name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # https://github.com/actions/checkout/releases/tag/v3.5.2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # https://github.com/actions/setup-go/releases/tag/v5.2.0
        with:
          go-version-file: ".go-version"
      -
        name: Go mod download
        run: go mod download -x
      -
        name: Run long tests
        run: go test -timeout=30m -tags=longtest ./...
