name: test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  GOPROXY: https://proxy.golang.org/

jobs:
  copywrite:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout Repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # https://github.com/actions/checkout/releases/tag/v3.5.3
      - name: Install copywrite
        uses: hashicorp/setup-copywrite@v1.1.2
      - name: Validate Header Compliance
        run: copywrite headers --plan

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # https://github.com/actions/checkout/releases/tag/v3.5.2
      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # https://github.com/actions/setup-go/releases/tag/v4.0.0
        with:
          go-version-file: ".go-version"
      - name: Go mod download
        run: go mod download -x
      - name: Go mod verify
        run: go mod verify
      - name: Run go fmt
        run: go run github.com/mh-cbon/go-fmt-fail ./...
      - name: Run tests
        run: go test -cover -covermode=atomic -timeout=5m -race ./...
